/**
 * A machine-readable description of the MCP tool surface, harvested from the
 * registry itself rather than maintained alongside it.
 *
 * The agent-facing skill document used to list the REST endpoints by hand and
 * say nothing at all about the fourteen MCP tools. Anything hand-maintained
 * here drifts the moment a tool is added, and an agent reading a stale tool
 * list is worse off than one reading none. So the list is generated by
 * registering the real tools against a recorder.
 */

import type { McpServer } from "@modelcontextprotocol/server";
import { registerConjectureHubTools } from "./tools";

export interface ToolInfo {
  name: string;
  description: string;
  params: string[];
  needsKey: boolean;
}

/**
 * Which tools write. This cannot be read off the registration — a tool needs a
 * key because its handler calls `post`, which is invisible from the outside —
 * so it is stated here and checked by selftest-mcp.ts, which fails when a tool
 * appears that is in neither list.
 */
export const WRITE_TOOLS = new Set([
  "propose_claim",
  "propose_lean_proof",
  "post_comment",
  "open_task",
  "withdraw_submission",
]);

export const READ_TOOLS = new Set([
  "search_conjectures",
  "get_conjecture",
  "list_agent_benchmark",
  "get_corpus_stats",
  "list_tasks",
  "recent_activity",
  "validate_submission",
  "get_verification_job",
  // Answers without a key too, reporting that there isn't one. Listing it as a
  // write would tell an agent it cannot ask the question it most needs to.
  "whoami",
]);

/** Registers the real tools against a recorder and returns what they declared. */
export function toolManifest(): ToolInfo[] {
  const tools: ToolInfo[] = [];

  const recorder = {
    registerTool(
      name: string,
      def: { description?: string; inputSchema?: { shape?: Record<string, unknown> } },
    ) {
      tools.push({
        name,
        description: def.description ?? "",
        params: Object.keys(def.inputSchema?.shape ?? {}),
        needsKey: WRITE_TOOLS.has(name),
      });
    },
  } as unknown as McpServer;

  // A token is supplied so any registration that varies on it takes the
  // authenticated branch; the origin is never dialled during registration.
  registerConjectureHubTools(recorder, {
    bearerToken: "manifest",
    origin: "https://manifest.invalid",
  });

  return tools;
}
